# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.wgt_video = myVideoWidget(self.centralwidget)
        self.wgt_video.setObjectName("wgt_video")
        self.gridLayout.addWidget(self.wgt_video, 0, 0, 8, 1)
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btn_open.setFont(font)
        self.btn_open.setObjectName("btn_open")
        self.gridLayout.addWidget(self.btn_open, 0, 1, 1, 1)
        self.btn_detect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_detect.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btn_detect.setFont(font)
        self.btn_detect.setObjectName("btn_detect")
        self.gridLayout.addWidget(self.btn_detect, 1, 1, 1, 1)
        self.btn_yolo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_yolo.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btn_yolo.setFont(font)
        self.btn_yolo.setObjectName("btn_yolo")
        self.gridLayout.addWidget(self.btn_yolo, 2, 1, 1, 1)
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btn_play.setFont(font)
        self.btn_play.setObjectName("btn_play")
        self.gridLayout.addWidget(self.btn_play, 3, 1, 1, 1)
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btn_stop.setFont(font)
        self.btn_stop.setObjectName("btn_stop")
        self.gridLayout.addWidget(self.btn_stop, 4, 1, 1, 1)
        self.btn_jietu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_jietu.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btn_jietu.setFont(font)
        self.btn_jietu.setObjectName("btn_jietu")
        self.gridLayout.addWidget(self.btn_jietu, 5, 1, 1, 1)
        self.btn_lupin = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lupin.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btn_lupin.setFont(font)
        self.btn_lupin.setObjectName("btn_lupin")
        self.gridLayout.addWidget(self.btn_lupin, 6, 1, 1, 1)
        self.lupintime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.lupintime.setMaximumSize(QtCore.QSize(300, 200))
        self.lupintime.setProperty("value", 2.0)
        self.lupintime.setObjectName("lupintime")
        self.gridLayout.addWidget(self.lupintime, 7, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sld_video = QtWidgets.QSlider(self.centralwidget)
        self.sld_video.setMaximum(100)
        self.sld_video.setOrientation(QtCore.Qt.Horizontal)
        self.sld_video.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sld_video.setObjectName("sld_video")
        self.horizontalLayout.addWidget(self.sld_video)
        self.lab_video = QtWidgets.QLabel(self.centralwidget)
        self.lab_video.setObjectName("lab_video")
        self.horizontalLayout.addWidget(self.lab_video)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "视频数据的信息管理及目标检测系统"))
        self.btn_open.setText(_translate("MainWindow", "打开文件"))
        self.btn_detect.setText(_translate("MainWindow", "基于HOG的检测算法"))
        self.btn_yolo.setText(_translate("MainWindow", "基于YOLO的检测算法"))
        self.btn_play.setText(_translate("MainWindow", "播放"))
        self.btn_stop.setText(_translate("MainWindow", "暂停"))
        self.btn_jietu.setText(_translate("MainWindow", "截图"))
        self.btn_lupin.setText(_translate("MainWindow", "录屏"))
        self.lab_video.setText(_translate("MainWindow", "0%"))
from myVideoWidget import myVideoWidget
